name: Update README

on:
  push:
    branches: [ main ]

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}  # Use the PAT from your secrets

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Include any other dependencies you might need

    - name: Run script
      run: python ./.github/scripts/generate_readme.py ${{ github.workspace }}

    - name: Commit and push if it changed
      run: |
        git diff
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        message="README.md is updated automatically"
        git commit -m "${message}" || echo "No changes to commit"
        git push
